### ISSUE TITLE
A514_spectral_count no-qvalue error_Kainan

### ISSUE THREAD

**Issue by kainan0601** [joshuayuanlab151/proteomics_analysis#1]
[kainan@terra2 ~]$ cd /scratch/user/kainan/
[kainan@terra2 kainan]$ /scratch/user/kainan/software/crux/crux-4.0.Linux.x86_64/bin/crux spectral-counts /scratch/user/kainan/data_dye/analysis_20210713_allsqtfromXH/percolator/one-06012021.new/percolator.target.psms.txt --output-dir ./count --measure RAW --protein-database /scratch/user/kainan/data_dye/db/database_A514_NoReNoStop.fasta --overwrite T
INFO: Writing results to output directory './count'.
INFO: CPU: tlogin-0502.cluster
INFO: Crux version: 4.0-b854e9b-2021-06-01
INFO: Mon Jul 19 10:15:34 CDT 2021
INFO: Beginning spectral-counts.
INFO: Reached protein 1000
INFO: Reached protein 2000
INFO: Reached protein 3000
INFO: Reached protein 4000
INFO: Reached protein 5000
INFO: Reached protein 6000
INFO: Total proteins found: 6457
WARNING: No data/headers found!
INFO: Number of matches:0
FATAL: The matches in /scratch/user/kainan/data_dye/analysis_20210713_allsqtfromXH/percolator/one-06012021.new/percolator.target.psms.txt do not have q-values.
Please either provide a file with q-values or set threshold-type to "none" or "custom."

**Comment by jiali0411** [comment]
1. check your `one-06012021.new/percolator.target.psms.txt` to see if it is empty. 
2. If yes, it is possible the percolator did not run successfully. Re-run the percolator step.
3. Make sure the `make-pin.pin` is a table without NA values 'nan'. 
4. Make sure the decoy prefix is the one you have in your database. Could be 'Reverse_' or 'decoy_', double check your sqt files.
